name: Attest

on:
  workflow_call:
    inputs:
      workload_identity_provider:
        required: true
        type: string
      service_account:
        required: true
        type: string
      project_id:
        type: string
      image_url:
        required: true
        type: string
      attestor_name:
        required: true
        type: string
      attestor_project_id:
        required: true
        type: string
      kms_key_project_id:
        required: true
        type: string
      kms_key_location:
        required: true
        type: string
      kms_keyring_name:
        required: true
        type: string
      kms_key_name:
        required: true
        type: string
      kms_key_version:
        required: true
        type: string
      runner:
        required: true
        type: string
      # remove if unused
      deploy_on:
        type: string
        default: 'refs/heads/main'
      # remove if unused
      environment:
        type: string

jobs:
  attest:
    name: Authentication and Attestation
    runs-on: ${{ inputs.runner }}
    permissions:
      contents: read
      packages: write
      # required for authentication to GCP
      id-token: write

    steps:
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ inputs.workload_identity_provider }}
          service_account: ${{ inputs.service_account }}
          project_id: ${{ inputs.project_id }}

      # https://cloud.google.com/binary-authorization/docs/making-attestations
      - name: Perform attestation
        run: |
          gcloud beta container binauthz attestations sign-and-create \
            --project="${{inputs.project_id}}" \
            --artifact-url="${{ inputs.image_url }}" \
            --attestor="${{inputs.attestor_name}}" \
            --attestor-project="${{inputs.attestor_project_id}}" \
            --keyversion-project="${{inputs.kms_key_project_id}}" \
            --keyversion-location="${{inputs.kms_key_location}}" \
            --keyversion-keyring="${{inputs.kms_keyring_name}}" \
            --keyversion-key="${{inputs.kms_key_name}}" \
            --keyversion="${{inputs.kms_key_version}}"