name: Attest

on:
  workflow_call:
    inputs:
      image_url:
        required: true
        type: string
      runner:
        required: true
        type: string
      deploy_on:
        type: string
        default: 'refs/heads/main'
      project_id:
        type: string
      environment:
        type: string

 #KMS_KEY_PROJECT_ID=skip-dev-7d22
 #KMS_KEY_LOCATION=europe
 #KMS_KEYRING_NAME=Dev-attestor-key
 #KMS_KEY_NAME=Attestor-test-key
 #KMS_KEY_VERSION=1
 #ATTESTATION_PROJECT_ID=kubernetes-dev-94b9
 #ATTESTOR_PROJECT_ID=kubernetes-dev-94b9
 #ATTESTOR_NAME=Testing-attestor
 #WORKLOAD_IDENTITY_FEDERATION_PROVIDER=projects/214581028419/locations/global/workloadIdentityPools/github-runner-deploy-pool/providers/github-provider
 #WORKLOAD_IDENTITY_FEDERATION_SERVICE_ACCOUNT=github-runner-deploy@skip-dev-7d22.iam.gserviceaccount.com

jobs:
  attest:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # required for authentication to GCP
      id-token: write

    steps:


      - id: auth
        name: Authenticate to GCP
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{env.WORKLOAD_IDENTITY_FEDERATION_PROVIDER}}
          service_account: ${{env.WORKLOAD_IDENTITY_FEDERATION_SERVICE_ACCOUNT}}
          project_id: ${{env.KMS_KEY_PROJECT_ID}}

      # https://cloud.google.com/binary-authorization/docs/making-attestations
      #TODO change all variables to comply with reuseable
      - name: Perform attestation
        run: |
          gcloud beta container binauthz attestations sign-and-create \
            --project="${{env.ATTESTATION_PROJECT_ID}}" \
            --artifact-url="${{ inputs.image_url }}" \
            --attestor="${{env.ATTESTOR_NAME}}" \
            --attestor-project="${{env.ATTESTOR_PROJECT_ID}}" \
            --keyversion-project="${{env.KMS_KEY_PROJECT_ID}}" \
            --keyversion-location="${{env.KMS_KEY_LOCATION}}" \
            --keyversion-keyring="${{env.KMS_KEYRING_NAME}}" \
            --keyversion-key="${{env.KMS_KEY_NAME}}" \
            --keyversion="${{env.KMS_KEY_VERSION}}"