name: Check Validity of Jsonnet Files

on:
  workflow_call:

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    
    steps:
      - name: Show full repository name
        run: "echo \"Repository: ${{ github.repository }}\""
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install go for jsonnetfmt
        uses: actions/setup-go@v5
        with: 
          go-version: 1.22

      - name: Install jsonnetfmt
        run: go install github.com/google/go-jsonnet/cmd/jsonnetfmt@latest

      - name: Validate jsonnet formatting
        run: |
          jsonnetfmt --test $(git ls-files '*.jsonnet' '*.libsonnet')

      - name: Print errors
        if: ${{ failure() }}
        run: |
          jsonnetfmt -i $(git ls-files '*.jsonnet' '*.libsonnet')
          git diff