name: Run Terraform

on:
  workflow_call:
    inputs:
      workload_identity_provider:
        required: true
        type: string
      service_account:
        required: true
        type: string
      image_tag_url:
        required: false
        type: string
        default: ''
    outputs:
      image_digest_url: 
        description: "Image URL with sha digest"
        value: ${{ jobs.get-image-digest-url.outputs.output1 }}


jobs:
  get-image-digest-url:
    name: Get Image Digest
    runs-on: ubuntu-latest
    outputs: 
      output1: ${{ steps.pull-inspect-image.outputs.msg }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ inputs.workload_identity_provider }}
          service_account: ${{ inputs.service_account }}

      - name: Pull and inspect image
        id: pull-inspect-image
        run: |
          docker pull ${{ inputs.image_url}}
          mystr=$(docker inspect --format='{{index .RepoDigests 0}}' ${{ inputs.image_url}})
          msg=$(printf '%s' $mystr | jq --raw-input --slurp '.' --join-output)
          echo "::set-output name=msg::$msg"

