name: Run Terraform

on:
  workflow_call:
    inputs:
      workload_identity_provider:
        required: true
        type: string
      service_account:
        required: true
        type: string
      image_url:
        required: false
        type: string
        default: ''

jobs:
  get-digest:
    name: Get Image Digest
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ inputs.workload_identity_provider }}
          service_account: ${{ inputs.service_account }}

      - name: Pull and inspect image
        id: pull-inspect-image
        run: |
          docker pull ${{ inputs.image_url}}
          mystr=$(docker inspect --format='{{index .RepoDigests 0}}' ${{ inputs.image_url}})
          msg=$(printf '%s' "$mystr" | jq --raw-input --slurp '.')
          echo "::set-output name=msg::$msg"
          echo "${{ steps.pull-inspect-image.outputs.msg }}"

      - name: Get image digest 
        id: get-digest
        run: |
          echo "${{ steps.pull-inspect-image.outputs.msg }}"
          gh api \
            -H "Accept: application/vnd.github+json" \
            /orgs/kartverket/packages/container/github-runner/versions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
